name: Update Fedora nightly

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Install Git
        run: dnf install -y git

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: dnf install -y copr-cli rpm-build rpmdevtools git

      - name: API stuff
        run: |
          mkdir -p ~/.config
          echo "${{ secrets.COPR_CONFIG }}" > ~/.config/copr

      - name: Do tarball and versions
        run: |
          git config --global --add safe.directory /__w/LeShade/LeShade

          BASE_VERSION=$(tr -d '[:space:]' < VERSION)

          DATE=$(date +%d%m%Y)
          HASH=$(git rev-parse --short HEAD)
          COUNT=$(git rev-list --count HEAD)

          SNAPSHOT_VERSION="${BASE_VERSION}+git.${DATE}.${COUNT}.${HASH}"

          sed -i "s/^Version:.*/Version: $SNAPSHOT_VERSION/" fedora/leshade-nightly.spec

          rpmdev-setuptree

          tar --transform "s|^|LeShade-$SNAPSHOT_VERSION/|" -czf ~/rpmbuild/SOURCES/LeShade-$SNAPSHOT_VERSION.tar.gz .

      - name: sendo to COPR (leshade-nightly)
        run: |
          rpmbuild -bs fedora/leshade-nightly.spec
          copr-cli build leshade-nightly ~/rpmbuild/SRPMS/*.src.rpm
